name: Ubuntu 22.04 ROS Humble (devel)

on:

  workflow_dispatch:

  schedule:
    - cron: '34 19 * * 0'

jobs:
  build:
    uses: ./.github/workflows/_ros2-ubuntu-build.yaml
    with:
      ubuntu_version: ubuntu-22.04
      ros_distro: humble
      container_image: osrf/ros:humble-desktop
      vcs_file: ros2-dvrk-devel.vcs
      colcon_skip_packages: dvrk_data dvrk_console
      # extra_apt_packages: qtbase5-dev   # example: add Qt5 packages specific to Humble
